import type {
  Asset,
  Capture,
  Identity,
  KnowledgeEntry,
  ObjectRef,
  Project,
  Relationship,
  Release,
} from "../../types";
import { findDiscoveries } from "../../hooks/discoveryEngine";
import { DISCOVERY_TYPE_META } from "../../hooks/discoveryEngine";
import { findOpportunities } from "../../hooks/opportunityEngine";
import { OPPORTUNITY_TYPE_META } from "../../hooks/opportunityEngine";
import { resolveObjectRef } from "../../hooks/relationshipDiscovery";
import type { DiscoveryContext } from "../../hooks/relationshipDiscovery";
import { buildChiefObservations } from "../../hooks/chief";
import "./Chief.css";

interface ChiefViewProps {
  identities: Identity[];
  projects: Project[];
  knowledgeEntries: KnowledgeEntry[];
  assets: Asset[];
  releases: Release[];
  captures: Capture[];
  relationships: Relationship[];
  onOpenObject: (ref: ObjectRef) => void;
}

// Forge's first voice, now a calmer and more complete one: a handful of
// observations, each shown in full — perspective text, which engine it
// traces back to, and a way to investigate further — rather than a
// dashboard or a feed. Nothing here is generated by Chief; every word
// already existed in the Perspective Layer, the Discovery Engine, or the
// Opportunity Engine before this component ever rendered it. The two
// sources are never blended into one look-alike list item — each keeps its
// own badge ("Understanding" for a Discovery, "Possibility" for an
// Opportunity) so the distinction the mission requires stays visible, not
// just technically true underneath.
function ChiefView({
  identities,
  projects,
  knowledgeEntries,
  assets,
  releases,
  captures,
  relationships,
  onOpenObject,
}: ChiefViewProps) {
  const discoveryContext: DiscoveryContext = {
    identities,
    projects,
    knowledgeEntries,
    assets,
    releases,
    captures,
    relationships,
  };

  const observations = buildChiefObservations(
    findDiscoveries(discoveryContext),
    findOpportunities(discoveryContext),
  );

  return (
    <section className="section-view">
      <h2 className="section-title">Chief</h2>
      <p className="section-subtitle">
        A few observations worth your attention — each traceable straight back to how Forge found it.
      </p>

      {observations.length === 0 ? (
        <div className="section-empty">
          <p className="section-empty-title">Nothing to observe yet.</p>
          <p className="section-empty-subtitle">
            As Forge notices patterns and openings in your work, Chief will bring the most meaningful ones here.
          </p>
        </div>
      ) : (
        <ul className="chief-observations">
          {observations.map((observation) => {
            if (observation.kind === "discovery") {
              const { discovery, perspective } = observation;
              const meta = DISCOVERY_TYPE_META[discovery.type];

              return (
                <li key={perspective.id} className="placeholder-card chief-observation">
                  <div className="chief-observation-meta">
                    <span className="badge chief-kind-badge chief-kind-discovery">Understanding</span>
                    <span className={`badge discovery-type-badge discovery-type-${discovery.type}`}>
                      {meta.icon} {meta.label}
                    </span>
                    <span className="discovery-confidence">
                      {Math.round(discovery.confidence * 100)}% confidence
                    </span>
                  </div>

                  {/* Chief's own words, verbatim from the Perspective Layer —
                      nothing here is reworded for this view. */}
                  <p className="chief-observation-text">{perspective.text}</p>

                  <div className="discovery-objects">
                    {discovery.objects.map((ref) => {
                      const resolved = resolveObjectRef(ref, discoveryContext);
                      // Same convention as everywhere else Related/Discovery
                      // links resolve an ObjectRef — skip quietly if the
                      // object no longer exists rather than showing a broken
                      // link.
                      if (!resolved) return null;

                      return (
                        <button
                          key={`${ref.type}-${ref.id}`}
                          className="discovery-object-link"
                          onClick={() => onOpenObject(ref)}
                        >
                          {resolved.icon} {resolved.label}
                        </button>
                      );
                    })}
                  </div>
                </li>
              );
            }

            const { opportunity, text } = observation;
            const meta = OPPORTUNITY_TYPE_META[opportunity.type];

            return (
              <li key={`opportunity:${opportunity.id}`} className="placeholder-card chief-observation">
                <div className="chief-observation-meta">
                  <span className="badge chief-kind-badge chief-kind-opportunity">Possibility</span>
                  <span className={`badge opportunity-type-badge opportunity-type-${opportunity.type}`}>
                    {meta.icon} {meta.label}
                  </span>
                </div>

                {/* Chief's own words for an Opportunity — composed once in
                    chief.ts (see composeOpportunityText), not reworded here. */}
                <p className="chief-observation-text">{text}</p>

                <div className="discovery-objects">
                  {opportunity.objects.map((ref) => {
                    const resolved = resolveObjectRef(ref, discoveryContext);
                    if (!resolved) return null;

                    return (
                      <button
                        key={`${ref.type}-${ref.id}`}
                        className="discovery-object-link"
                        onClick={() => onOpenObject(ref)}
                      >
                        {resolved.icon} {resolved.label}
                      </button>
                    );
                  })}
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}

export default ChiefView;
